module-title = "Embedded Protocols"
input-descriptor-file = "gen/descriptor.pb"
main-page-content-file = "sabledocs-main.md"
output-dir = "gen/docs"
enable-lunr-search = true
footer-content = ""
repository-type = "github"
repository-url = "https://github.com/atilova-garden/embedded.protocols"
repository-branch = "master"
repository-dir = "proto"
ignore-comments-after = ["@exclude"]
ignore-comment-lines-containing = ["buf:lint"]
hidden-packages = []
member-ordering = "preserve"
markdown-extensions = ["fenced_code", "nl2br"]
